@startuml fxuiPackageDiagram
title Package Diagram for fxui
namespace fxui {
    namespace src {
        namespace main.java.bibtek {
            class AddBookController
            class App
            class BaseBookController
            class BookItemView
            class CreateUserController
            class DigitsField
            class EditBookController
            class LibraryController
            class LoginPageController
            class SceneChangerController
            class SettingsController
            class TermsController
            class Toast
            class ViewBookController

        }
        namespace test.java.bibtek {
            namespace ui {
                class AddBookSceneTest
                class LibrarySceneTest
            }
        }
        
    }
}


@enduml